### ISSUE TITLE
Test colab/binder button

### ISSUE THREAD

**Issue by DPGoldstein** [process-intelligence-research/computational_practicum_lecture_coding#3]
Because the repository is private, it cannot be accessed by colab and binder. Thus, the colab and binder button included in the top level readme are not working and cannot be implemented and tested properly. This needs to be fixed once the repository is published.

**Comment by giacomolastrucci** [comment]
Now the repo is public. However, the buttons didn't work and I fixed it.
Just for reference, the URL to a certain branch for Binder should be:

`https://mybinder.org/v2/gh/process-intelligence-research/computational_practicum_lecture_coding/main`

rather than:

`https://mybinder.org/v2/gh/process-intelligence-research/computational_practicum_lecture_coding/tree/main`

While for Google Colab:

`https://colab.research.google.com/github/process-intelligence-research/computational_practicum_lecture_coding/blob/main`

rather than:

`https://colab.research.google.com/github/process-intelligence-research/computational_practicum_lecture_coding/tree/main`
